[project]
name = "polo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "maliang[opt]>=3.1.5",
    "nuitka>=2.8.9",
    "pdf2docx>=0.5.8",
]
