name: Build Executable with Nuitka

on:
  push:
    branches:
      - master # Trigger on pushes to the 'master' branch

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest] # Build on multiple OS platforms

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Cache pip dependencies
        uses: actions/cache@v4 # Update to v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          pip install -r requirements.txt -r requirements-dev.txt

      - name: Build executable with Nuitka
        uses: Nuitka/Nuitka-Action@v1.4 # Use stable version of Nuitka Action
        with:
          script-name: main.py # Replace with your script name
          mode: app # For macOS app bundle, use standalone for others

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }} Build
          path: |
            build/*.exe  # For Windows
            build/*.bin  # For Linux
            build/*.app/**/*  # For macOS
          include-hidden-files: true
